'use strict';
const frame=document.getElementById('app'),results=document.getElementById('results'),status=document.getElementById('status');
const req=r=>new Promise((resolve,reject)=>{r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});
const done=tx=>new Promise((resolve,reject)=>{tx.oncomplete=resolve;tx.onabort=()=>reject(tx.error||new Error('aborted'));});
const wait=async fn=>{for(let n=0;n<300;n++){if(fn())return;await new Promise(r=>setTimeout(r,20));}throw new Error('Timeout aguardando interface');};
function check(value,label){const li=document.createElement('li');li.className=value?'pass':'fail';li.textContent=`${value?'OK':'FALHOU'} — ${label}`;results.append(li);if(!value)throw new Error(label);}
async function rejects(promise,code){try{await promise;return false;}catch(e){return !code||e.message===code;}}
const equal=(a,b)=>JSON.stringify(a)===JSON.stringify(b);
document.querySelectorAll('[data-width]').forEach(b=>b.onclick=()=>{frame.style.width=`${b.dataset.width}px`;});
document.getElementById('run').onclick=async()=>{
  document.getElementById('run').disabled=true;results.replaceChildren();status.textContent='Executando…';
  const urls=[],connections=[];
  const scriptURL=text=>{const url=URL.createObjectURL(new Blob([text],{type:'text/javascript'}));urls.push(url);return url;};
  try{
    const source=await fetch('../js/chronicles-storage.js').then(r=>r.text());
    const stamp='2026-01-01T00:00:00.000Z';
    const old={id:'chronicle-legacy-test',schemaVersion:1,name:'Horizonte de Teste',synopsis:'Arquivo preservado',type:'campaign',hasCover:true,createdAt:stamp,updatedAt:stamp};
    const person={id:'participant-legacy-test',chronicleId:old.id,name:'Felipe',createdAt:stamp,updatedAt:stamp};
    const canvas=document.createElement('canvas');canvas.width=960;canvas.height=540;
    const ctx=canvas.getContext('2d');ctx.fillStyle='#131738';ctx.fillRect(0,0,960,540);ctx.fillStyle='#d5c4ff';ctx.font='48px sans-serif';ctx.fillText('CRÔNICA · TESTE',100,290);
    const coverBlob=await new Promise(r=>canvas.toBlob(r,'image/webp',0.8));
    let api,db,prefix,storageURL;
    for(const version of [1,2,3]){
      prefix=`confrontosV1Test${crypto.randomUUID().replaceAll('-','')}`;
      const open=indexedDB.open(`${prefix}Chronicles`,version);
      open.onupgradeneeded=()=>{
        const s=open.result.createObjectStore('chronicles',{keyPath:'id'});
        ['createdAt','updatedAt','type'].forEach(k=>s.createIndex(k,k));
        open.result.createObjectStore('chronicleCovers',{keyPath:'chronicleId'});
        if(version>=2){const links=open.result.createObjectStore('chronicleCastLinks',{keyPath:['chronicleId','characterId']});['chronicleId','characterId'].forEach(k=>links.createIndex(k,k));}
        if(version>=3)open.result.createObjectStore('chronicleParticipants',{keyPath:'id'}).createIndex('chronicleId','chronicleId');
      };
      const legacy=await req(open),tx=legacy.transaction([...legacy.objectStoreNames],'readwrite');
      tx.objectStore('chronicles').add(old);tx.objectStore('chronicleCovers').add({chronicleId:old.id,blob:coverBlob,width:960,height:540});
      if(version>=2)tx.objectStore('chronicleCastLinks').add({chronicleId:old.id,characterId:'character-fixture-1'});
      if(version>=3)tx.objectStore('chronicleParticipants').add(person);
      await done(tx);legacy.close();
      storageURL=scriptURL(source.replaceAll('cronicasRessonancia',prefix));
      await new Promise((resolve,reject)=>{const script=document.createElement('script');script.src=storageURL;script.onload=resolve;script.onerror=reject;document.body.append(script);});
      api=window.ChroniclesStorage;
      check(equal(await api.getChronicle(old.id),old),`Upgrade v${version} → v6 preserva Crônica e schema 1`);
      check(await (await api.getChronicleCover(old.id)).blob.text()===await coverBlob.text(),`Upgrade v${version} → v6 preserva Blob da capa`);
      check((await api.listChronicleCastIds(old.id)).length===(version>=2?1:0),`Upgrade v${version} → v6 preserva Elenco`);
      check(equal((await api.listChronicleParticipants(old.id)).participants,version>=3?[person]:[]),`Upgrade v${version} → v6 preserva Participantes`);
      db=await req(indexedDB.open(`${prefix}Chronicles`));connections.push(db);
      const inspection=db.transaction([...db.objectStoreNames]);
      check(db.version===6 && db.objectStoreNames.length===14,'Banco v6 possui exatamente quatorze stores');
      check(equal(inspection.objectStore('confrontationCharacterLinks').keyPath,['confrontationId','characterId']) && inspection.objectStore('confrontationCharacterLinks').indexNames.length===1,'Vínculo tem chave composta e somente índice confrontationId');
      check(['chronicleConfrontations','confrontationAdversaries'].every(k=>inspection.objectStore(k).keyPath==='id' && inspection.objectStore(k).indexNames.length===1 && !inspection.objectStore(k).index(inspection.objectStore(k).indexNames[0]).unique),'Confrontos e adversários têm IDs e um índice não exclusivo cada');
    }
    const battle=await api.createConfrontation(old.id,{name:'Ataque à instalação',description:'Proteger a passagem.'});
    check(Object.keys(battle).sort().join(',')==='active,chronicleId,createdAt,description,id,name,updatedAt','Confronto contém apenas os campos persistidos, incluindo active');
    const twin=await api.createConfrontation(old.id,{name:battle.name});
    check(twin.id!==battle.id && (await api.listConfrontations(old.id))[0].id===twin.id,'Nomes repetidos e listagem por criação mais recente');
    check(await rejects(api.createConfrontation(old.id,{name:' '}),'INVALID_CONFRONTATION_NAME') && await rejects(api.createConfrontation(old.id,{name:'x'.repeat(121)}),'INVALID_CONFRONTATION_NAME') && await rejects(api.createConfrontation(old.id,{name:'N',description:'x'.repeat(1201)}),'INVALID_CONFRONTATION_DESCRIPTION'),'Validação de nome e descrição');
    check((await api.listConfrontationCharacterIds(battle.id)).length===0,'Confronto não inclui Elenco automaticamente');
    check(await rejects(api.replaceConfrontationCharacters(battle.id,['character-outside-1'],{expectedCharacterIds:[]}),'CHARACTER_NOT_IN_CAST'),'Novas inclusões fora do Elenco são recusadas');
    await api.replaceConfrontationCharacters(battle.id,['character-fixture-1'],{expectedCharacterIds:[]});
    await api.replaceConfrontationCharacters(twin.id,['character-fixture-1'],{expectedCharacterIds:[]});
    check((await api.listConfrontationCharacterIds(twin.id)).length===1,'Mesmo personagem pode pertencer a dois Confrontos');
    const links=await req(db.transaction('confrontationCharacterLinks').objectStore('confrontationCharacterLinks').getAll());
    check(links.every(r=>Object.keys(r).sort().join(',')==='characterId,confrontationId'),'Vínculos persistem somente IDs');
    await api.replaceChronicleCast(old.id,[]);
    await api.replaceConfrontationCharacters(battle.id,['character-fixture-1'],{expectedCharacterIds:['character-fixture-1']});
    check((await api.listConfrontationCharacterIds(battle.id)).length===1,'Remoção do Elenco preserva vínculo existente');
    check(await rejects(api.replaceConfrontationCharacters(battle.id,[],{expectedCharacterIds:[]}),'COMBAT_SELECTION_CONFLICT'),'Conflito da seleção não apaga vínculos');
    const enemy=await api.createConfrontationAdversary(battle.id,{name:'Sentinela'});
    check(Object.keys(enemy).sort().join(',')==='confrontationId,createdAt,id,name,updatedAt','Campos numéricos ausentes não são inventados');
    check(await rejects(api.createConfrontationAdversary(battle.id,{name:'X',pvCurrent:2}),'INVALID_ADVERSARY_PV') && await rejects(api.createConfrontationAdversary(battle.id,{name:'X',pvCurrent:-1,pvMax:10}),'INVALID_ADVERSARY_PV') && await rejects(api.createConfrontationAdversary(battle.id,{name:'X',defense:NaN}),'INVALID_ADVERSARY_NUMBERS'),'PV em par e números inválidos recusados');
    const revised=await api.updateConfrontationAdversary(battle.id,enemy.id,{name:'Sentinela',pvCurrent:20,pvMax:10,defense:12},{expectedUpdatedAt:enemy.updatedAt});
    check(revised.id===enemy.id && revised.createdAt===enemy.createdAt && revised.pvCurrent===20,'Adversário mantém ID; PV acima do máximo não é reduzido');
    const unchangedEnemy=await api.updateConfrontationAdversary(battle.id,enemy.id,{name:'Sentinela',pvCurrent:20,pvMax:10,defense:12},{expectedUpdatedAt:revised.updatedAt});
    check(unchangedEnemy.updatedAt===revised.updatedAt,'Adversário sem mudanças não altera data');
    check(await rejects(api.updateConfrontationAdversary(battle.id,enemy.id,{name:'Conflito'},{expectedUpdatedAt:enemy.updatedAt}),'ADVERSARY_UPDATE_CONFLICT'),'Conflito individual de adversário');
    const clearOptional=await api.createConfrontationAdversary(twin.id,{name:'Opcional',pvCurrent:1,pvMax:4,defense:9});
    const cleared=await api.updateConfrontationAdversary(twin.id,clearOptional.id,{name:'Opcional'},{expectedUpdatedAt:clearOptional.updatedAt});
    check(!('pvCurrent' in cleared) && !('pvMax' in cleared) && !('defense' in cleared),'Remover campos opcionais não persiste zeros nem null');
    const before=await api.getConfrontation(battle.id);
    const noop=await api.updateConfrontation(battle.id,{name:before.name,description:before.description},{expectedUpdatedAt:before.updatedAt});
    check(noop.updatedAt===before.updatedAt,'Salvar Confronto sem mudança não altera timestamp');
    const originalPut=IDBObjectStore.prototype.put;
    IDBObjectStore.prototype.put=function(...args){if(this.name==='chronicles')throw new Error('TEST_ROLLBACK');return originalPut.apply(this,args);};
    check(await rejects(api.updateConfrontationAdversary(battle.id,enemy.id,{name:'Não salvar'},{expectedUpdatedAt:revised.updatedAt}),'TEST_ROLLBACK'),'Falha após escrita parcial aborta adversário');
    IDBObjectStore.prototype.put=originalPut;
    check((await api.listConfrontationAdversaries(battle.id))[0].name==='Sentinela' && (await api.getConfrontation(battle.id)).updatedAt===before.updatedAt,'Rollback preserva adversário e Confronto');
    const competition=await Promise.allSettled(['A','B'].map(name=>api.updateConfrontationAdversary(battle.id,enemy.id,{name},{expectedUpdatedAt:revised.updatedAt})));
    check(competition.filter(r=>r.status==='fulfilled').length===1 && competition.some(r=>r.status==='rejected' && r.reason.message==='ADVERSARY_UPDATE_CONFLICT'),'Edições simultâneas do mesmo adversário: uma vence, outra conflita');
    check(await rejects(api.deleteConfrontationAdversary(twin.id,enemy.id,{expectedUpdatedAt:revised.updatedAt}),'ADVERSARY_NOT_FOUND'),'Não remove adversário de outro Confronto');
    const originalDelete=IDBObjectStore.prototype.delete;
    IDBObjectStore.prototype.delete=function(...args){if(this.name==='confrontationAdversaries')throw new Error('TEST_DELETE_ROLLBACK');return originalDelete.apply(this,args);};
    check(await rejects(api.deleteChronicle(old.id),'TEST_DELETE_ROLLBACK'),'Falha em cascata aborta exclusão de Crônica');
    IDBObjectStore.prototype.delete=originalDelete;
    check(await api.getChronicle(old.id) && await api.getChronicleCover(old.id) && (await api.listChronicleParticipants(old.id)).participants.length===1 && (await api.listConfrontationCharacterIds(battle.id)).length===1 && (await api.listConfrontationAdversaries(battle.id)).length===1,'Cascata abortada preserva registros nas stores existentes e novas');
    IDBObjectStore.prototype.delete=function(...args){if(this.name==='confrontationAdversaries')throw new Error('TEST_DELETE_ROLLBACK');return originalDelete.apply(this,args);};
    check(await rejects(api.deleteConfrontation(battle.id,{expectedUpdatedAt:(await api.getConfrontation(battle.id)).updatedAt}),'TEST_DELETE_ROLLBACK'),'Falha na exclusão do Confronto aborta transação');
    IDBObjectStore.prototype.delete=originalDelete;
    check(await api.getConfrontation(battle.id) && (await api.listConfrontationCharacterIds(battle.id)).length===1 && (await api.listConfrontationAdversaries(battle.id)).length===1,'Rollback de Confronto preserva seus filhos');
    const [html,appSource]=await Promise.all([fetch('../index.html').then(r=>r.text()),fetch('../script.js').then(r=>r.text())]);
    const appURL=scriptURL(appSource.replaceAll('cronicasRessonancia',prefix));
    await new Promise(resolve=>{frame.onload=resolve;frame.srcdoc=html.replace('<head>',`<head><base href="${new URL('../',location.href)}">`)
      .replace(/src="js\/chronicles-storage.js[^"]*"/,`src="${storageURL}"`).replace(/src="script.js[^"]*"/,`src="${appURL}"`);});
    const w=frame.contentWindow,d=w.document,el=id=>d.getElementById(id),ui=w.ConfrontationsUI,uiStorage=w.ChroniclesStorage;
    await wait(()=>!el('characterManagerView').hidden && typeof w.openConfrontationCreation==='function');
    const ids=['character-fixture-1','character-fixture-2','character-fixture-3'];
    let manager=w.readCharacterManager()||w.createEmptyCharacterManager();
    for(const [i,name] of ['Dylann','Luke','Talia'].entries()){
      const character=w.createEmptyCharacterState();character.fields.nome=name;character.fields.classe='Vanguarda';character.fields.nivel=2;character.fields.pvAtual=18;character.fields.pvMax=30;character.fields.pvTemporarios=3;
      w.writeStoredCharacter(ids[i],character);manager=w.setCharacterSummary(manager,ids[i],await w.createCharacterSummary(character));
    }
    w.writeCharacterManager(manager);await api.replaceChronicleCast(old.id,ids);
    const originalSheets=ids.map(id=>JSON.stringify(w.readStoredCharacter(id)));
    w.showManagerSection('chronicles');await w.showChroniclesIndex();
    await w.openChronicleDetail(old.id,1,d.querySelector(`[data-chronicle-id="${old.id}"] button`));
    w.setChronicleDetailSection('encounters');await ui.renderIndex();
    check(el('confrontationIndex').children.length===2,'Aba lista Confrontos reais');
    el('newConfrontation').click();check(!el('confrontationForm').hidden,'Novo Confronto abre formulário básico');
    el('confrontationForm').requestSubmit();check(el('confrontationName').getAttribute('aria-invalid')==='true','Nome obrigatório no formulário');
    el('confrontationName').value='Batalha criada na interface';el('confrontationDescriptionInput').value='Descrição de teste';el('confrontationForm').requestSubmit();
    await wait(()=>!el('confrontationView').hidden && el('confrontationTitle').textContent==='Batalha criada na interface');
    const created=(await api.listConfrontations(old.id)).find(r=>r.name==='Batalha criada na interface');
    check(created && !el('confrontationView').hidden && (await api.listConfrontationCharacterIds(created.id)).length===0,'Criar abre ambiente próprio sem incluir combatentes');
    el('backFromConfrontation').click();await wait(()=>!el('chronicleDetailView').hidden && !el('chroniclePanelEncounters').hidden);
    await ui.renderIndex(created.id);
    check(d.activeElement.closest('[data-confrontation-id]')?.dataset.confrontationId===created.id,'Voltar retorna à aba e restaura foco no registro');
    await ui.open(created.id);el('editConfrontation').click();await wait(()=>!el('confrontationName').disabled && el('confrontationName').value===created.name);
    el('confrontationName').value='Ataque revisado';el('confrontationForm').requestSubmit();
    await wait(()=>el('confrontationTitle').textContent==='Ataque revisado');
    check((await api.getConfrontation(created.id)).createdAt===created.createdAt,'Editar preserva ID e createdAt');
    el('editConfrontation').click();await wait(()=>!el('confrontationName').disabled && el('confrontationName').value==='Ataque revisado');
    const conflictVersion=await api.getConfrontation(created.id);
    await api.updateConfrontation(created.id,{name:'Atualizado em outra aba',description:''},{expectedUpdatedAt:conflictVersion.updatedAt});
    el('confrontationName').value='Rascunho mantido';el('confrontationForm').requestSubmit();await wait(()=>el('confrontationFormFeedback').dataset.kind==='error');
    check(el('confrontationName').value==='Rascunho mantido' && !el('confrontationForm').hidden,'Conflito de metadados mantém formulário');el('cancelConfrontationForm').click();
    await api.updateConfrontation(created.id,{name:'Ataque revisado',description:'Descrição de teste'},{expectedUpdatedAt:(await api.getConfrontation(created.id)).updatedAt});await ui.open(created.id);
    el('selectConfrontationCharacters').click();await wait(()=>el('confrontationSelectionList').querySelectorAll('input').length===3);
    const toggle=id=>{const input=el('confrontationSelectionList').querySelector(`[data-character-id="${id}"]`);input.click();};
    toggle(ids[0]);toggle(ids[1]);el('confrontationSelectionForm').requestSubmit();
    await wait(()=>el('confrontationSelectionForm').hidden && el('confrontationCharacters').querySelectorAll('article').length===2);
    check((await api.listConfrontationCharacterIds(created.id)).length===2 && el('confrontationCharacters').textContent.includes('PV 18 / 30') && el('confrontationCharacters').textContent.includes('3 PV temporários'),'Seleção múltipla persistida e recursos apenas em consulta');
    check(!el('confrontationCharacters').querySelector('input') && originalSheets.every((s,i)=>JSON.stringify(w.readStoredCharacter(ids[i]))===s),'Consulta não edita recursos nem fichas');
    const priorOrder=[...w.readCharacterManager().order];
    await w.duplicateCharacterById(ids[1]);
    const duplicate=w.readCharacterManager().order.find(id=>!priorOrder.includes(id));
    const imported=await w.storeImportedCharacterAsNew(w.readStoredCharacter(ids[1]));
    check(duplicate && imported && duplicate!==imported && !(await api.listConfrontationCharacterIds(created.id)).includes(duplicate) && !(await api.listConfrontationCharacterIds(created.id)).includes(imported),'Duplicação e importação não herdam vínculos de Confronto');
    await ui.open(created.id);
    el('selectConfrontationCharacters').click();await wait(()=>!el('confrontationCharacterSearch').disabled && el('confrontationSelectionList').querySelectorAll('input').length===3);
    el('confrontationCharacterSearch').value='luk';el('confrontationCharacterSearch').dispatchEvent(new w.Event('input',{bubbles:true}));
    check(el('confrontationSelectionList').querySelectorAll('input').length===1 && el('confrontationSelectionList').textContent.includes('Luke'),'Busca somente por nome preserva seleção oculta');
    toggle(ids[1]);el('cancelConfrontationSelection').click();check((await api.listConfrontationCharacterIds(created.id)).length===2,'Cancelar seleção não persiste');
    el('selectConfrontationCharacters').click();await wait(()=>el('confrontationSelectionList').querySelectorAll('input').length===3);toggle(ids[2]);
    await api.replaceConfrontationCharacters(created.id,[ids[0]],{expectedCharacterIds:ids.slice(0,2)});el('confrontationSelectionForm').requestSubmit();await wait(()=>el('confrontationSelectionFeedback').textContent.includes('outra aba'));
    check(!el('confrontationSelectionForm').hidden && el('confrontationSelectionList').querySelector(`[data-character-id="${ids[2]}"]`).checked,'Conflito entre seleções preserva escolhas locais');el('cancelConfrontationSelection').click();
    await api.replaceConfrontationCharacters(created.id,ids.slice(0,2),{expectedCharacterIds:[ids[0]]});
    el('selectConfrontationCharacters').click();await wait(()=>el('confrontationSelectionList').querySelectorAll('input').length===3);toggle(ids[2]);
    await api.replaceChronicleCast(old.id,ids.slice(0,2));el('confrontationSelectionForm').requestSubmit();
    await wait(()=>el('confrontationSelectionFeedback').dataset.kind==='error');
    check(!el('confrontationSelectionForm').hidden && el('confrontationSelectionList').querySelector(`[data-character-id="${ids[2]}"]`).checked,'Inclusão removida do Elenco durante edição é recusada, preservando escolha');
    el('cancelConfrontationSelection').click();await api.replaceChronicleCast(old.id,[ids[1]]);await ui.open(created.id);
    check(el('confrontationCharacters').textContent.includes('Fora do Elenco'),'Vínculo existente fora do Elenco permanece visível');
    const updatedCharacter=w.readStoredCharacter(ids[1]);updatedCharacter.fields.nome='Luke Atualizado';updatedCharacter.fields.pvAtual=9;w.writeStoredCharacter(ids[1],updatedCharacter);
    await ui.open(created.id);check(el('confrontationCharacters').textContent.includes('Luke Atualizado') && el('confrontationCharacters').textContent.includes('PV 9 / 30'),'Nova renderização resolve nome e PV atuais');
    w.removeStoredCharacter(ids[0]);w.writeCharacterManager(w.removeCharacterFromManager(w.readCharacterManager(),ids[0]));
    await ui.open(created.id);
    check(el('confrontationCharacters').textContent.includes('Personagem indisponível') && (await api.listConfrontationCharacterIds(created.id)).includes(ids[0]),'Personagem excluído preserva referência indisponível');
    el('selectConfrontationCharacters').click();await wait(()=>el('confrontationSelectionList').querySelectorAll('input').length===2);toggle(ids[0]);el('confrontationSelectionForm').requestSubmit();await wait(()=>el('confrontationSelectionForm').hidden);
    check(!(await api.listConfrontationCharacterIds(created.id)).includes(ids[0]) && (await api.listConfrontationCharacterIds(battle.id)).includes(ids[0]),'Remover combatente altera somente um vínculo');
    el('addConfrontationAdversary').click();el('confrontationAdversaryName').value='Demônio de Cinzas';el('confrontationAdversaryForm').requestSubmit();
    await wait(()=>el('confrontationAdversaryForm').hidden && el('confrontationAdversaries').querySelector('[data-adversary-id]'));
    let foe=(await api.listConfrontationAdversaries(created.id))[0];
    check(foe.name==='Demônio de Cinzas' && el('confrontationAdversaries').textContent.includes('PV não informado'),'Adversário sem valores não recebe números inventados');
    el('confrontationAdversaries').querySelector('button').click();await wait(()=>el('confrontationAdversaryName').value===foe.name && !el('confrontationAdversaryName').disabled);
    el('confrontationAdversaryPVCurrent').value='40';el('confrontationAdversaryForm').requestSubmit();
    check(el('confrontationAdversaryFeedback').dataset.kind==='error','PV parcial é rejeitado na interface');
    el('confrontationAdversaryPVMax').value='40';el('confrontationAdversaryDefense').value='14';el('confrontationAdversaryForm').requestSubmit();
    await wait(()=>el('confrontationAdversaryForm').hidden && el('confrontationAdversaries').textContent.includes('DEF 14'));
    check((await api.listConfrontationAdversaries(created.id))[0].id===foe.id,'Editar adversário preserva identidade');
    el('confrontationAdversaries').querySelector('button').click();await wait(()=>!el('confrontationAdversaryName').disabled && el('confrontationAdversaryName').value===foe.name);
    foe=(await api.listConfrontationAdversaries(created.id))[0];
    await api.updateConfrontationAdversary(created.id,foe.id,{name:'Outra aba'},{expectedUpdatedAt:foe.updatedAt});
    el('confrontationAdversaryName').value='Meu rascunho';el('confrontationAdversaryForm').requestSubmit();await wait(()=>el('confrontationAdversaryFeedback').textContent.includes('outra aba'));
    check(el('confrontationAdversaryName').value==='Meu rascunho' && !el('confrontationAdversaryForm').hidden,'Conflito mantém edição local aberta');el('cancelConfrontationAdversary').click();
    el('addConfrontationAdversary').click();el('confrontationAdversaryName').value='Falha deve preservar';
    w.ChroniclesStorage={...uiStorage,createConfrontationAdversary:async()=>{throw new Error('TEST_UI_FAILURE');}};
    el('confrontationAdversaryForm').requestSubmit();await wait(()=>el('confrontationAdversaryFeedback').dataset.kind==='error' && !el('confrontationAdversaryName').disabled);
    check(el('confrontationAdversaryName').value==='Falha deve preservar','Falha de transação preserva formulário');w.ChroniclesStorage=uiStorage;el('cancelConfrontationAdversary').click();
    let releaseOpening;const openingGate=new Promise(resolve=>{releaseOpening=resolve;});
    w.ChroniclesStorage={...uiStorage,listConfrontationCharacterIds:async(...args)=>{await openingGate;return uiStorage.listConfrontationCharacterIds(...args);}};
    el('selectConfrontationCharacters').click();el('cancelConfrontationSelection').click();releaseOpening();w.ChroniclesStorage=uiStorage;
    await new Promise(resolve=>setTimeout(resolve,40));check(el('confrontationSelectionForm').hidden,'Resposta atrasada não reabre seleção cancelada');
    el('addConfrontationAdversary').click();el('confrontationAdversaryName').value='Não salvar';el('backFromConfrontation').click();
    check(!el('modalOverlay').hidden && !el('confrontationView').hidden,'Saída com rascunho pede confirmação');w.closeModal();el('cancelConfrontationAdversary').click();
    let release,calls=0;const gate=new Promise(resolve=>{release=resolve;});
    w.ChroniclesStorage={...uiStorage,createConfrontationAdversary:async(...args)=>{calls++;await gate;return uiStorage.createConfrontationAdversary(...args);}};
    el('addConfrontationAdversary').click();el('confrontationAdversaryName').value='Duplo clique';el('confrontationAdversaryForm').requestSubmit();el('confrontationAdversaryForm').requestSubmit();
    w.showManagerSection('characters');check(!el('confrontationView').hidden,'Navegação bloqueada durante transação');release();await wait(()=>el('confrontationAdversaryForm').hidden);w.ChroniclesStorage=uiStorage;
    check(calls===1,'Duplo salvar executa uma operação');
    await ui.open(created.id);
    const victim=(await api.listConfrontationAdversaries(created.id))[0];
    let victimRow=[...el('confrontationAdversaries').children].find(r=>r.dataset.adversaryId===victim.id);victimRow.querySelectorAll('button')[1].click();
    check(el('modalDescription').textContent.includes(victim.name),'Confirmação identifica adversário');w.closeModal();check((await api.listConfrontationAdversaries(created.id)).length===2,'Cancelar remoção mantém adversários');
    victimRow.querySelectorAll('button')[1].click();[...el('modalActions').children].find(b=>b.textContent==='Remover adversário').click();
    await wait(()=>el('confrontationAdversaries').querySelectorAll('[data-adversary-id]').length===1);
    check(!(await api.listConfrontationAdversaries(created.id)).some(a=>a.id===victim.id),'Remoção confirmada exclui somente adversário escolhido');
    await api.createConfrontationAdversary(created.id,{name:'X'.repeat(120),pvCurrent:0,pvMax:100,defense:12});await ui.open(created.id);
    for(const width of [1440,768,390,320]){
      frame.style.width=`${width}px`;await new Promise(r=>setTimeout(r,100));
      check(d.documentElement.scrollWidth<=width,`Tela operacional sem overflow em ${width}px`);
      el('addConfrontationAdversary').click();
      check(d.documentElement.scrollWidth<=width && el('confrontationAdversaryName').getBoundingClientRect().height>=44,`Formulário e toque confortáveis em ${width}px`);el('cancelConfrontationAdversary').click();
      el('selectConfrontationCharacters').click();await wait(()=>!el('confrontationCharacterSearch').disabled);
      check(d.documentElement.scrollWidth<=width && el('confrontationSelectionForm').querySelector('button[type="submit"]').getBoundingClientRect().height>=44,`Seleção acessível em ${width}px`);el('cancelConfrontationSelection').click();
      el('confrontationAdversaries').querySelectorAll('button')[1].click();await wait(()=>el('modalActions').firstElementChild===d.activeElement);
      check(d.documentElement.scrollWidth<=width && el('modalActions').firstElementChild.textContent==='Cancelar',`Confirmação sem overflow e foco seguro em ${width}px`);w.closeModal();
    }
    frame.style.width='1440px';
    check(!el('confrontationActivityTitle') && db.objectStoreNames.length===14,'Coluna vazia de atividade removida; sem store de combate adicional');
    el('editConfrontation').click();await wait(()=>!el('confrontationName').disabled && el('confrontationName').value==='Ataque revisado');el('deleteConfrontation').click();
    check(el('modalDescription').textContent.includes('Ataque revisado'),'Exclusão identifica Confronto');
    [...el('modalActions').children].find(b=>b.textContent==='Excluir Confronto').click();
    await wait(()=>!el('chronicleDetailView').hidden && !el('chroniclePanelEncounters').hidden && el('confrontationForm').hidden);
    check(await rejects(api.getConfrontation(created.id),'CONFRONTATION_NOT_FOUND') && !(await req(db.transaction('confrontationCharacterLinks').objectStore('confrontationCharacterLinks').index('confrontationId').getAll(created.id))).length && !(await req(db.transaction('confrontationAdversaries').objectStore('confrontationAdversaries').index('confrontationId').getAll(created.id))).length,'Excluir Confronto remove as três entidades');
    check((await api.listChronicleParticipants(old.id)).participants.length===1 && w.readStoredCharacter(ids[1]).fields.nome==='Luke Atualizado','Excluir Confronto preserva Participantes e fichas');
    await api.deleteChronicle(old.id);
    check(!await api.getChronicle(old.id) && !await api.getChronicleCover(old.id) && !(await req(db.transaction('chronicleParticipants').objectStore('chronicleParticipants').getAll())).length && !(await req(db.transaction('chronicleConfrontations').objectStore('chronicleConfrontations').getAll())).length && !(await req(db.transaction('confrontationCharacterLinks').objectStore('confrontationCharacterLinks').getAll())).length && !(await req(db.transaction('confrontationAdversaries').objectStore('confrontationAdversaries').getAll())).length,'Excluir Crônica remove integralmente dados dependentes');
    const previewChronicle=await api.createChronicle({name:'Horizonte de Teste',synopsis:'Dados exclusivos desta execução de teste.',type:'campaign',cover:{blob:coverBlob,width:960,height:540}});
    await api.replaceChronicleCast(previewChronicle.id,[ids[1],ids[2]]);
    const previewBattle=await api.createConfrontation(previewChronicle.id,{name:'Ataque à instalação',description:'O grupo avança pelo portão norte. Os adversários aguardam junto à passagem.'});
    await api.replaceConfrontationCharacters(previewBattle.id,[ids[1],ids[2]],{expectedCharacterIds:[]});
    await api.createConfrontationAdversary(previewBattle.id,{name:'Demônio de Cinzas',pvCurrent:35,pvMax:50,defense:14});
    await api.createConfrontationAdversary(previewBattle.id,{name:'Sentinela',pvCurrent:18,pvMax:18,defense:12});
    await w.showChroniclesIndex();await w.openChronicleDetail(previewChronicle.id,1,d.querySelector(`[data-chronicle-id="${previewChronicle.id}"] button`));await ui.open(previewBattle.id);
    const persisted=JSON.stringify(await api.getConfrontation(previewBattle.id));
    const docSource=frame.srcdoc;await new Promise(resolve=>{frame.onload=resolve;frame.srcdoc=docSource;});
    const reloaded=frame.contentWindow;await wait(()=>!reloaded.document.getElementById('characterManagerView').hidden && !!reloaded.ConfrontationsUI);
    check(JSON.stringify(await reloaded.ChroniclesStorage.getConfrontation(previewBattle.id))===persisted && (await reloaded.ChroniclesStorage.listConfrontationCharacterIds(previewBattle.id)).length===2 && (await reloaded.ChroniclesStorage.listConfrontationAdversaries(previewBattle.id)).length===2,'Reload preserva Confronto, seleção e adversários');
    reloaded.showManagerSection('chronicles');await reloaded.showChroniclesIndex();await reloaded.openChronicleDetail(previewChronicle.id,1,reloaded.document.querySelector(`[data-chronicle-id="${previewChronicle.id}"] button`));await reloaded.ConfrontationsUI.open(previewBattle.id);
    status.textContent=`Concluído: ${results.children.length} verificações aprovadas.`;
  }catch(error){console.error(error);status.textContent=`Falha: ${error.message}`;}
  finally{connections.forEach(db=>db.close());urls.forEach(url=>URL.revokeObjectURL(url));document.getElementById('run').disabled=false;}
};
